force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Error Log object to hold all handled/unhandled error in a single place.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Platform event to handle efficient Exception/Log handling</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <label>Current User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandlerTest.cls
/**********************************************************************************************
* @Author:      Tirthankar - Salesforce COE 
* @Date:        24th June 20200
* @Description: This test class covers for LogEventTriggerHandler,GenericEventErrorLogger,GenericEventErrorLoggerHelper
***********************************************************************************************/
@isTest
public with sharing class LogEventTriggerHandlerTest {
	@isTest static void testValidLogEvent()
    {
    	Log__e logEventInstance = new Log__e(Component_Name__c = 'Test Component',
                                             Error_Message__c = 'Test Error Message');
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(logEventInstance);
        Test.stopTest();
        System.assertEquals(true, sr.isSuccess());
		System.assertEquals(1, [SELECT Id FROM Error_Log__c].size()); 
    }
    @isTest static void testInValidLogEvent()
    {
        Log__e logEventInstance = new Log__e(Component_Name__c = 'Test Component',
                                             Error_Message__c = 'Test Error Message',
                                             Current_User__c = 'testId');
        Test.startTest();
        try
        {
        	Database.SaveResult sr = EventBus.publish(logEventInstance);    
        }catch(Exception ee){
            GenericEventErrorLogger.publishEventFromException(ee, 'Test Component');
        }
        try
        {
        	Account accountInstance;
            accountInstance.Name = 'Test Account';
        }catch(Exception ee) //Null Pointer Exception
        {
        	GenericEventErrorLogger.publishEventFromException(ee, 'Test Exception Component');
        }
        try
        {
        	insert new Account(Name = null);
        }catch(DMLException de)
        {
        	GenericEventErrorLogger.publishEventFromException(de, 'Test Exception Component');
        }
        Test.stopTest();       
		System.assertEquals(0, [SELECT Id FROM Error_Log__c].size());                        
    }
}