force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Error Log object to hold all handled/unhandled error in a single place.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <label>Error Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Lightning Component</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException,.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Flow_User__c.field-meta.xml
<CustomField>
    <fullName>Flow_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <description>This field will store the governor limit details</description>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Line_number__c.field-meta.xml
<CustomField>
    <fullName>Line_number__c</fullName>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Row_Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Row_Exception_Message__c</fullName>
    <label>Row Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/Error_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Configuration</label>
    <pluralLabel>Error Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Custom_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Custom_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for Custom Platform Event</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for Custom Platform Event</inlineHelpText>
    <label>Extended Class For Custom PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Custom_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Custom_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Custom PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Platform event to handle efficient Exception/Log handling</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <label>Current User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <label>Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandler.cls
/**********************************************************************************************
* @Author:      Tirthankar - Salesforce COE 
* @Date:        24th June 20200
* @Description: Trigger handler class for LogEventTrigger
***********************************************************************************************/
public with sharing class LogEventTriggerHandler {
    
    public static void afterInsert(list<Log__e> logEventList)
    {
        Error_Log_Configuration__mdt errorLogEventInstance = CustomMetadataUtility.getLogErrorMetadata();
        if(errorLogEventInstance!=null && 
           String.isNotEmpty(errorLogEventInstance.Extended_Class_For_Custom_PE__c) && 
           !errorLogEventInstance.Is_Using_Packaged_Code_For_Custom_PE__c)
        {
        	//Dynamically fetch the batch handler class and invoke the method
            Type classType = Type.forName(errorLogEventInstance.Extended_Class_For_Custom_PE__c);  
            ErrorLogExtendedInterface errorLogInterface = (ErrorLogExtendedInterface)classType.newInstance();
            errorLogInterface.execute(logEventList);    
        }else
        {
        	insertIntoLoggerObject(logEventList);    
        }
    }    
    
    public static void insertIntoLoggerObject(list<Log__e> logEventList)
    {   
        try
        {
            list<Error_Log__c> errorLogList = new list<Error_Log__c>();
            for(Log__e logInst : logEventList)
            {
                errorLogList.add( new Error_Log__c(
                    Component_Name__c = logInst.Component_Name__c ,
                    Error_Message__c = logInst.Error_Message__c ,
                    Error_Source__c = logInst.Error_Type__c ,                
                    Row_Exception_Message__c = logInst.Row_Exception_Message__c ,
                    Stack_Trace__c = logInst.Error_Stacktrace__c ,
                    Line_Number__c = logInst.Line_Number__c ,
                    Limits__c = logInst.Limits__c,
                    Exception_Type__c = logInst.Exception_Type__c,
                    Record_Id__c = logInst.Record_Id__c,
                    Flow_User__c = logInst.Current_User__c                
                ));    
            }
            list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);      
        }catch(Exception ee)
        {
            if (EventBus.TriggerContext.currentContext().retries < 4) 
            {
                // Condition isn't met, so try again later.
                throw new EventBus.RetryableException( ApplicationConstant.RETRYERROR );
            }else
            {
                //probably add a seperate record into error log of platform event type
            }
        }
        
    }
}