force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Error Log object to hold all handled/unhandled error in a single place.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <label>Error Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Lightning Component</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <description>This field will store the details of exception type, such as DmlException, ListException, SObjectException,.</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>START</fullName>
            </value>
            <value>
                <fullName>EXECUTE</fullName>
            </value>
            <value>
                <fullName>FINISH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/Error_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Configuration</label>
    <pluralLabel>Error Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Batch_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Batch_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for BatchApexErrorEvent</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for BatchApexErrorEvent</inlineHelpText>
    <label>Extended Class For Batch PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Batch_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Batch_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Batch PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApexErrorEventTriggerHandler.cls
/**********************************************************************************************
* @Author:      Tirthankar - Salesforce COE 
* @Date:        24th June 20200
* @Description: Trigger handler class for BatchApexErrorEventTrigger
* @TestClass:   BatchApexErrorEventTest 
***********************************************************************************************/
global class BatchApexErrorEventTriggerHandler {
    
    global static void afterInsert(list<BatchApexErrorEvent> batchApexErrorList)
    {
        Error_Log_Configuration__mdt errorLogEventInstance = CustomMetadataUtility.getLogErrorMetadata();
        if(errorLogEventInstance!=null && 
           String.isNotEmpty(errorLogEventInstance.Extended_Class_For_Batch_PE__c) && 
           !errorLogEventInstance.Is_Using_Packaged_Code_For_Batch_PE__c)
        {
        	//Dynamically fetch the batch handler class and invoke the method
            Type classType = Type.forName(errorLogEventInstance.Extended_Class_For_Batch_PE__c);  
            ErrorLogExtendedInterface errorLogInterface = (ErrorLogExtendedInterface)classType.newInstance();
            errorLogInterface.execute(batchApexErrorList);    
        }else
        {
        	insertIntoLoggerObject(batchApexErrorList);    
        }
    }
    
    public static void insertIntoLoggerObject(list<BatchApexErrorEvent> batchApexErrorList)
    {
        try
        {
            set<Id> asyncApexJobIds = new set<Id>();
            list<Error_Log__c> errorLogList = new list<Error_Log__c>();
            for(BatchApexErrorEvent batchInst : batchApexErrorList)
            {
                asyncApexJobIds.add(batchInst.AsyncApexJobId);
            }
            Map<Id,AsyncApexJob> asyncIdJobMap = new Map<Id,AsyncApexJob>([SELECT Id, ApexClass.Name 
                                                                           FROM AsyncApexJob 
                                                                           WHERE Id IN :asyncApexJobIds]
                                                                         );                       
            for(BatchApexErrorEvent batchInst : batchApexErrorList)
            {            
                //instantiate the error logging object and feed the error information from PE               
                errorLogList.add( new Error_Log__c(
                    Component_Name__c = asyncIdJobMap.get(batchInst.AsyncApexJobId)!=null ? asyncIdJobMap.get(batchInst.AsyncApexJobId).ApexClass.Name : '' ,
                    Error_Message__c = batchInst.Message ,
                    Error_Source__c = ApplicationConstant.BATCHAPEX ,                
                    Phase__c = batchInst.Phase ,
                    Stack_Trace__c = batchInst.StackTrace ,
                    Exception_Type__c = batchInst.ExceptionType ,
                    Record_Id__c = batchInst.JobScope                
                ));                 
            }                      
            list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);     
        }catch(Exception ee)
        {
            if (EventBus.TriggerContext.currentContext().retries < 4) 
            {
                // Condition isn't met, so try again later.
                throw new EventBus.RetryableException(ApplicationConstant.RETRYERROR);
            }else
            {
                 //probably add a seperate record into error log of platform event type
            }
        }        
    }
    
}