force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Error Log object to hold all handled/unhandled error in a single place.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error_Source__c.field-meta.xml
<CustomField>
    <fullName>Error_Source__c</fullName>
    <description>This field will store the source of error from where the error has invoked.</description>
    <label>Error Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Lightning Component</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Flow_User__c.field-meta.xml
<CustomField>
    <fullName>Flow_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will store the salesforce Id of the impacted record.</description>
    <label>Record Id</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/Error_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Configuration</label>
    <pluralLabel>Error Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Flow_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Flow_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for FlowExecutionErrorEvent</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for FlowExecutionErrorEvent</inlineHelpText>
    <label>Extended Class For Flow PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Flow_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Flow_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Flow PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowExecutionEventTriggerHandler.cls
/**********************************************************************************************
* @Author:      Tirthankar - Salesforce COE 
* @Date:        24th June 20200
* @Description: Trigger handler class for FlowExecutionEventTrigger
* @TestClass:   FlowExecutionEventTriggerHandlerTest 
***********************************************************************************************/
public with sharing class FlowExecutionEventTriggerHandler 
{
    public static void afterInsert(list<FlowExecutionErrorEvent> flowErrorList)
    {
        Error_Log_Configuration__mdt errorLogEventInstance = CustomMetadataUtility.getLogErrorMetadata();        
        if(errorLogEventInstance!=null && 
           String.isNotEmpty(errorLogEventInstance.Extended_Class_For_Flow_PE__c) && 
           !errorLogEventInstance.Is_Using_Packaged_Code_For_Flow_PE__c)
        {
        	//Dynamically fetch the batch handler class and invoke the method
            Type classType = Type.forName(errorLogEventInstance.Extended_Class_For_Flow_PE__c);  
            ErrorLogExtendedInterface errorLogInterface = (ErrorLogExtendedInterface)classType.newInstance();
            errorLogInterface.execute(flowErrorList);    
        }else
        {
        	insertIntoLoggerObject(flowErrorList);    
        }
    }

	public static void insertIntoLoggerObject(list<FlowExecutionErrorEvent> flowErrorList)
    {
    	try
        {
            list<Error_Log__c> errorLogList = new list<Error_Log__c>();
        	for(FlowExecutionErrorEvent flowErrorInstance : flowErrorList)
            {
                 //instantiate the error logging object and feed the error information from PE 
                errorLogList.add(new Error_Log__c(
                    Record_Id__c = flowErrorInstance.RelatedRecordId, 
                    Error_Message__c = flowErrorInstance.ErrorMessage,
                    Component_Name__c = flowErrorInstance.FlowApiName,
                    Flow_User__c= flowErrorInstance.UserId,
                    Error_Source__c = ApplicationConstant.FLOW 
                ));    
            }
            list<DataBase.SaveResult> errorLogSaveResults = Database.insert(errorLogList);
        }catch(Exception ee)
        {
            if (EventBus.TriggerContext.currentContext().retries < 4) 
            {
                // Condition isn't met, so try again later.
                throw new EventBus.RetryableException( ApplicationConstant.RETRYERROR );
            }else
            {
                //probably add a seperate record into error log of platform event type  
            }
        }
    }
}