force-app/main/default/objects/Error_Log_Configuration__mdt/Error_Log_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Error Log Configuration</label>
    <pluralLabel>Error Log Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Batch_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Batch_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for BatchApexErrorEvent</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for BatchApexErrorEvent</inlineHelpText>
    <label>Extended Class For Batch PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Custom_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Custom_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for Custom Platform Event</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for Custom Platform Event</inlineHelpText>
    <label>Extended Class For Custom PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Extended_Class_For_Flow_PE__c.field-meta.xml
<CustomField>
    <fullName>Extended_Class_For_Flow_PE__c</fullName>
    <description>This class name can be implemented to write own custom logic to override the existing one with Extended class for FlowExecutionErrorEvent</description>
    <inlineHelpText>This class name can be implemented to write own custom logic to override the existing one with Extended class for FlowExecutionErrorEvent</inlineHelpText>
    <label>Extended Class For Flow PE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Batch_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Batch_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Batch PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Custom_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Custom_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Custom PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Error_Log_Configuration__mdt/fields/Is_Using_Packaged_Code_For_Flow_PE__c.field-meta.xml
<CustomField>
    <fullName>Is_Using_Packaged_Code_For_Flow_PE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Using Packaged Code For Flow PE?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomMetadataUtility.cls
public inherited sharing class CustomMetadataUtility {
    public static Error_Log_Configuration__mdt getLogErrorMetadata()
    {
        try
        {
            return [SELECT Id,MasterLabel,DeveloperName,Extended_Class_For_Batch_PE__c,
                    Extended_Class_For_Custom_PE__c,Extended_Class_For_Flow_PE__c,
                    Is_Using_Packaged_Code_For_Batch_PE__c,Is_Using_Packaged_Code_For_Custom_PE__c,
                    Is_Using_Packaged_Code_For_Flow_PE__c 
                    FROM Error_Log_Configuration__mdt WHERE DeveloperName=: ApplicationConstant.CUSTOM_METADATA_NAME LIMIT 1];
        }catch(Exception ee)
        {
            throw ee;
        }
    }
}